Repository secureCodeBox/documentation, pull requests merged in 2020-10, with the labels that each got.

#12 Add a helper script to create and template new blog posts
  .envrc
  .gitignore
  bin/create_post.sh
Labels: documentation

#15 Describe how the doc is structured
  README.md
Labels: documentation

#16 Use the right image url in frontmatter
  blog/2020-09-08-blinmaker.md
  static/img/Logo_Black.svg
  static/img/Logo_Color.svg
  static/img/Logo_White.svg
  static/img/blog/2020-09-08-blini.jpg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
Labels: documentation

#18 Restructure docs to new structure
  README.md
  docs/contributing/conventions.md
  docs/contributing/integrating-a-hook.md
  docs/contributing/integrating-a-scanner.md
  docs/contributing/operator.md
  docs/getting-started/first-scans.md
  docs/getting-started/installation.md
  docs/how-tos/automatically-repeating-scans.md
  docs/how-tos/scanning-networks.md
  docs/how-tos/scanning-web-applications.md
  docs/user-guide/automatically-repeating-scans.md
  docusaurus.config.js
  scripts/docs.build.js
  scripts/sidebar.build.js
  scripts/utils/config.js
  src/pages/index.js
Labels: documentation

#20 Fix some spell and Markdwon errors
  README.md
Labels: documentation

#21 First Blog Post about v2
  blog/2020-10-12-whats-going-on.md
  blog/2020-10-14-why-securecodebox-version-2.md
  blog/2020-10-16-sundown-and-eol-of-securecodebox-v1.md
  static/img/blog/2020-10-12-commits.png
  static/img/blog/2020-10-12-javier-allegue-barros-unsplash.jpg
Labels: documentation

#22 For unknown reason footer links do not work in truncated teasers
  blog/2020-10-12-whats-going-on.md
Labels: documentation

#23 Add API / CRD Docs
  docs/api/crds/cascading-rule.md
  docs/api/crds/parse-definition.md
  docs/api/crds/scan-completion-hook.md
  docs/api/crds/scan-type.md
  docs/api/crds/scan.md
  docs/api/crds/scheduled-scan.md
  docs/api/finding.md
  scripts/docs.build.js
  scripts/utils/config.js
Labels: documentation

#19 Documentation Versioning
  README.md
  package.json
Labels: documentation

#24 Article about sundown and EOL of version 1
  blog/2020-10-15-sundown-and-eol-of-version-1.md
  blog/2020-10-16-sundown-and-eol-of-securecodebox-v1.md
  static/img/blog/2020-10-15-cute-kitten.jpg
  static/img/blog/2020-10-15-sundown.jpg
Labels: documentation

#27 Update Repo References
  README.md
  blog/2020-10-12-whats-going-on.md
  docs/how-tos/scanning-networks.md
  scripts/utils/config.js
Labels: documentation

#29 Expand Install Guides
  docs/getting-started/first-scans.md
  docs/getting-started/installation.md
Labels: documentation

#30 Rename the image of early blog post
  blog/2020-10-12-whats-going-on.md
  static/img/blog/2020-10-12-Fingerpost.jpg
Labels: blog

#32 Add missing telemetry page to new docs
  docs/telemetry.md
Labels: documentation

#28 Draft for release post
  blog/2020-10-16-release-of-securecodebox-version-2.md
  static/img/blog/2020-10-16-firework.jpg
Labels: blog

#33 Fix the URLs to the images
  blog/2020-10-12-whats-going-on.md
  blog/2020-10-15-sundown-and-eol-of-version-1.md
  blog/2020-10-16-release-of-securecodebox-version-2.md
Labels: blog, bug

#34 Use theright version number
  docs/getting-started/installation.md
Labels: bug, documentation

#36 Remove individual version from docs
  docs/getting-started/first-scans.md
  docs/getting-started/installation.md
Labels: documentation

#38 Bugfixing Imprint Link
  docusaurus.config.js
Labels: bug

#37 Improve getting started documentation
  docs/getting-started/first-scans.md
Labels: documentation
