Repository secureCodeBox/documentation, pull requests merged in 2020-11, with the labels that each got.

#47 Scanner Contribution Guide
  docs/api/crds.md
  docs/contributing/integrating-a-scanner.md
  docs/contributing/integrating-a-scanner/cascading-rules-dir.md
  docs/contributing/integrating-a-scanner/chart.yaml.md
  docs/contributing/integrating-a-scanner/examples-dir.md
  docs/contributing/integrating-a-scanner/parser-dir.md
  docs/contributing/integrating-a-scanner/readme.md
  docs/contributing/integrating-a-scanner/scanner-dir.md
  docs/contributing/integrating-a-scanner/templates-dir.md
  docs/contributing/integrating-a-scanner/values.yaml.md
  package-lock.json
  scripts/utils/config.js
Labels: documentation

#49 Add config for nvm
  .nvmrc
  README.md
  package.json
Labels: bug, documentation

#53 Vagrant install documentation
  docs/getting-started/installation.md
Labels: documentation

#54 Adding a contribution guide for integration-tests
  docs/contributing/integrating-a-scanner/integration-tests.md
Labels: documentation, enhancement

#55 Add integration test readme to docs sidebar
  scripts/utils/config.js
Labels: bug, documentation

#56 Add integration test docu to sidebar in main branch
  scripts/utils/config.js
Labels: bug

#57 Add Docs for ttlSecondsAfterFinished Fields of Parse and Hook CRD
  docs/api/crds/parse-definition.md
  docs/api/crds/scan-completion-hook.md
Labels: documentation, enhancement

#59 Document new FailedJobsHistoryLimit Property
  docs/api/crds/scheduled-scan.md
Labels: documentation, enhancement
