Repository secureCodeBox/documentation, pull requests merged in 2021-08, with the labels that each got.

#103 Fixed Broken Edit Links
  scripts/docs.build.js
Labels: bug

#109 Fix Broken Hook Links
  docs/hooks.md
Labels: bug, documentation

#107 Adding Whatweb icon
  static/img/integrationIcons/Whatweb.svg
Labels: enhancement

#105 Update list of supported kubernetes versions
  docs/getting-started/installation.md
Labels: documentation

#106 Adding new blog post about windows scanners (PingCastle)
  blog/2021-08-09-integrating-windows-scanners.md
  static/img/blog/2021-08-09-windows.jpg
Labels: blog

#108 Adding a how-to use your local docker images to the "Integrate a new scanner" tutorial
  docs/contributing/integrating-a-scanner/values.yaml.md
Labels: documentation
