Repository secureCodeBox/documentation, pull requests merged in 2021-07, with the labels that each got.

#89 Fixing function to copy files from main repo
  scripts/docs.build.js
Labels: bug

#87 Refactored the demo-apps name
  docs/contributing/integrating-a-hook/integration-tests.md
  docs/contributing/integrating-a-scanner.md
  docs/contributing/integrating-a-scanner/examples-dir.md
  docs/contributing/integrating-a-scanner/integration-tests.md
  docs/how-tos/scanning-networks.md
Labels: documentation

#91 Revert "Update npm dependencies and switch to lockfile version 2 (npm…
  package-lock.json
Labels: bug

#90 Rename lurcher to lurker
  docs/api/crds/scan-type.md
  docs/getting-started/uninstallation.md
  src/puml/2020-11-04-why-securecodebox-version-2/architecture-v2.puml
Labels: enhancement

#98 Fix Broken Findings Download Links
  .gitignore
  scripts/docs.build.js
  scripts/utils/config.js
  scripts/utils/scannerReadme.mustache
Labels: documentation

#99 Update to latest beta
  CONTRIBUTORS.md
  package-lock.json
  package.json
Labels: enhancement

#101 Add search 🔍
  docusaurus.config.js
  package-lock.json
  package.json
  src/css/custom.css
Labels: enhancement

#94 Update Documentation to secureCodeBox v3 Findings Format
  docs/api/finding.md
  docs/contributing/integrating-a-scanner/parser-dir.md
Labels: documentation
