Repository secureCodeBox/documentation, pull requests merged in 2021-09, with the labels that each got.

#114 Fixes for Tutorial: How-To Network Scanning
  docs/how-tos/scanning-networks.md
Labels: documentation

#111 Maintenance/update docs
  docs/api/crds/parse-definition.md
  docs/api/crds/scan-type.md
  docs/contributing/integrating-a-scanner/parser-dir.md
  docs/contributing/integrating-a-scanner/templates-dir.md
Labels: documentation

#113 Blogpost: How we work (closes #112)
  blog/2021-09-07-how-we-work.md
  static/img/blog/2021-09-07-notes.jpg
Labels: blog

#115 Adds a troubleshooting readme to the docs
  docs/getting-started/troubleshooting.md
  scripts/utils/config.js
Labels: documentation, enhancement

#116 Landing Page Overhaul
  README.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/Accoordion.tsx
  src/components/FlipCard.tsx
  src/components/Integration.tsx
  src/components/RoleCard.tsx
  src/components/Section.tsx
  src/css/_breakpoints.scss
  src/css/_mixins.scss
  src/css/accordion.module.scss
  src/css/custom.css
  src/css/flipcard.module.scss
  src/css/integration.module.scss
  src/css/styles.module.scss
  src/features.json
  src/features.json.license
  src/landingpageContent.js
  src/layouts/Sections.tsx
  src/pages/index.js
  src/pages/index.tsx
  src/pages/styles.module.scss
  src/types/scss.d.ts
  static/img/Desktop_Screenshots.png
  static/img/Logo_iteratec_rgb_black_SZ_rz.svg
  static/img/Logo_iteratec_rgb_white_SZ_rz.svg
  static/img/OWASP_Logo_Black.svg
  static/img/OWASP_Logo_White.svg
  static/img/features/close.svg
  static/img/features/code.svg
  static/img/features/content.svg
  static/img/features/graph.svg
  static/img/features/monitoring.svg
  static/img/features/quick.svg
  static/img/features/scanning.svg
  static/img/features/sdlc.svg
  static/img/features/testing.svg
  static/img/features/tick.svg
  static/img/roles/jh_small.jpg
  static/img/roles/rfe_hoch.jpg
  static/img/roles/rfe_hoch_cropped.jpg
  static/img/roles/sst_hoodie_hoch.jpg
  static/img/roles/sst_hoodie_hoch_cropped.jpg
  static/img/sponsors/Logo_sda-se.png
  static/img/sponsors/Logo_secura.svg
  static/img/sponsors/Logo_timo-pagel-it-consulting.png
  tsconfig.json
Labels: documentation, enhancement

#118 Add OWASP Logo and Link to new Landing Page
  docusaurus.config.js
  src/css/custom.css
  static/img/OWASP_Logo_Black.svg
  static/img/OWASP_Logo_White.svg
Labels: documentation

#120 Document Navbar Icon CSS Classes
  src/css/custom.css
Labels: documentation

#124 Fixes broken titles in light mode
  src/css/styles.module.scss
Labels: bug

#125 Fixed broken links in documentation
  docs/api/crds/cascading-rule.md
  docs/api/crds/parse-definition.md
  docs/api/crds/scan.md
  docs/api/crds/scheduled-scan.md
  docs/contributing/integrating-a-hook/integration-tests.md
  docs/contributing/integrating-a-scanner/integration-tests.md
  docs/contributing/integrating-a-scanner/parser-dir.md
  docs/how-tos/scanning-networks.md
Labels: bug
