Repository secureCodeBox/documentation, pull requests merged in 2022-05, with the labels that each got.

#247 Adding missing images for new scanner
  static/img/integrationIcons/ZAP Advanced.svg
  static/img/integrationIcons/nuclei.svg
  static/img/integrationIcons/semgrep.svg
Labels: documentation

#257 Fix documented values for resourceInclusion modes
  docs/how-tos/autodiscovery.md
Labels: bug, documentation

#256 :books: Adding community contribution criteria and lists
  docs/community-features/_category_.json
  docs/community-features/scanners-and-hooks.md
  docs/community-features/windows-scanners.md
  docs/contributing/contribution-criteria.md
  docs/experimental/_category_.json
Labels: documentation, enhancement, planned
