Repository secureCodeBox/documentation, pull requests merged in 2022-04, with the labels that each got.

#240 Issue 21 context boundary
  .gitignore
  Makefile
  bin/create_post.sh
  blog/2021-07-20-the-architecture-of-securecodebox-v2.md
  docs/architecture/03_system_scope_and_context.md
  docs/architecture/05_building_block_view.md
  docs/architecture/06_runtime_view.md
  docs/architecture/07_deployment_view.md
  docs/architecture/09_architecture_decisions/_category_.json
  docs/architecture/09_architecture_decisions/index.md
  docs/architecture/10_adr/_category_.json
  docs/architecture/10_quality_requirements.md
  docs/architecture/11_technical_risks.md
  docs/architecture/12_glossary.md
  docs/architecture/index.md
  scripts/docs.build.js
  scripts/utils/config.js
  src/puml/_theme.ipuml
  static/img/blog/2021-06-07-architecture-v1.png
  static/img/blog/2021-06-07-architecture-v1.puml
  static/img/blog/2021-07-20-architecture-v2.png
  static/img/blog/2021-07-20-architecture-v2.puml
  static/img/docs/architecture/building-blocks-whitebox-level-1.png
  static/img/docs/architecture/business-context-diagram.png
  static/img/docs/architecture/context-boundary-diagram.png
  static/img/docs/architecture/deployment-cluster-internal-central-scans.png
  static/img/docs/architecture/deployment-cluster-namespace-internal.png
  static/img/docs/architecture/kubernetes-diagram.png
  static/img/docs/architecture/runtime-basic-scan-via-kubectl.png
  static/img/docs/architecture/runtime-basic-scan-via-kubectl.puml
Labels: documentation, planned

#246 Add Autodiscovery how to article
  docs/how-tos/autodiscovery.md
Labels: documentation

#252 Fix that DefectDojo imports is done with ReadWrite hook
  static/img/docs/architecture/runtime-basic-scan-via-kubectl.png
  static/img/docs/architecture/runtime-basic-scan-via-kubectl.puml
Labels: bug, documentation

#250 Added documentation for the testing concept
  docs/contributing/test-concept/_category_.json
  docs/contributing/test-concept/hook-test.md
  docs/contributing/test-concept/index.md
  docs/contributing/test-concept/operator-test.md
  docs/contributing/test-concept/scanner-test.md
Labels: documentation, planned

#253 Fixing endpoint address of AWS S3
  docs/getting-started/installation.md
Labels: bug, documentation, planned
