Repository secureCodeBox/documentation, pull requests merged in 2022-07, with the labels that each got.

#264 Adding helm repo update note to troubleshooting
  docs/getting-started/troubleshooting.md
Labels: documentation, enhancement

#266 Redirected subdomain docs to main secureCodebox domain
  build/_redirects
Labels: maintainance

#268 Add project roadmap from OWASP project site
  docs/architecture/index.md
Labels: documentation
