Repository secureCodeBox/documentation, pull requests merged in 2022-03, with the labels that each got.

#226 "How we handled Log4J using SCB" Blog Post
  blog/2022-01-18-log4shell.md
  static/img/blog/2022-02-24-burninglog.jpg
Labels: blog, planned

#211 Architecture Documentation
  CONTRIBUTORS.md
  docs/architecture/functional/crosscutting-concepts.md
  docs/architecture/functional/quality-requirements.md
  docs/architecture/functional/risks-and-technical-debt.md
  docs/architecture/introduction.md
  docs/architecture/technical/building-block-view.md
  docs/architecture/technical/deployment-view.md
  docs/architecture/technical/runtime-view.md
  static/img/architecture/BusinessContextDiagram.png
  static/img/architecture/Kubernetes_Diagram.png
  static/img/architecture/TechnicalContextDiagram.png
  static/img/architecture/UseCaseDiagramSCB.png
Labels: documentation, planned

#234 Fix path to static images
  docs/architecture/introduction.md
  docs/architecture/technical/building-block-view.md
Labels: bug, documentation

#235 Migrate Architecture Doc into Official Arc42 Template
  .gitignore
  README.md
  docs/architecture/01_introduction_and_goals.md
  docs/architecture/02_architecture_constraints.md
  docs/architecture/03_system_scope_and_context.md
  docs/architecture/04_solution_strategy.md
  docs/architecture/05_building_block_view.md
  docs/architecture/06_runtime_view.md
  docs/architecture/07_deployment_view.md
  docs/architecture/08_concepts.md
  docs/architecture/09_architecture_decisions.md
  docs/architecture/10_adr/_category_.json
  docs/architecture/11_quality_requirements.md
  docs/architecture/12_technical_risks.md
  docs/architecture/13_glossary.md
  docs/architecture/adr/_category_.json
  docs/architecture/functional/crosscutting-concepts.md
  docs/architecture/functional/risks-and-technical-debt.md
  docs/architecture/index.md
  docs/architecture/technical/building-block-view.md
  docs/architecture/technical/deployment-view.md
  docs/architecture/technical/runtime-view.md
  scripts/utils/config.js
  static/img/docs/architecture/business-context-diagram.png
  static/img/docs/architecture/deployment-cluster-internal-central-scans.png
  static/img/docs/architecture/deployment-cluster-namespace-internal.png
  static/img/docs/architecture/kubernetes-diagram.png
  static/img/docs/architecture/technical-context-diagram.png
  static/img/docs/architecture/use-case-diagram.png
Labels: documentation, planned

#241 Update README to reflect new scripts functionality
  README.md
Labels: documentation
