Repository secureCodeBox/documentation, pull requests merged in 2023-07, with the labels that each got.

#314 Rename repository path
  docs/contributing/local-deployment.md
Labels: documentation

#318 Activate dependabot version updates
  .github/dependabot.yml
Labels: maintainance

#327 Updated Docusaurus from v2.3.1 to latest version v2.4.1
  package-lock.json
  package.json
Labels: maintainance

#329 Update renamed makefile targets
  docs/contributing/integrating-a-hook/makefile.md
  docs/contributing/integrating-a-scanner/makefile.md
Labels: bug, documentation
