Repository secureCodeBox/documentation, pull requests merged in 2023-03, with the labels that each got.

#291 fix typo in documentation
  docs/getting-started/installation.md
Labels: bug, documentation

#299 Renamed the telemetry file so it is autogenerated in the sidebar by docusurus
  docs/09-telemetry.md
Labels: bug

#305 #304 Move article about backporting under contributing section
  docs/backports/_category_.json
  docs/contributing/backports.md
Labels: documentation
